### ISSUE TITLE
Регистрация участников без клуба

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#128]
- [ ] Отмечать отсутствие клуба у участника в гуе #124
- [ ] Изменение логики распределения по подгруппам с учетом пользователей, у которых нет клуба #125
- [ ] Изменение логики сохранения в БД участников, у которых нет клуба #126
- [ ] Изменение логики получения из БД участников, у которых нет клуба #127
